// File generated from our OpenAPI spec by Stainless.

package com.configure_me_emcees_prod_testing_5.api.models.transactions

import com.configure_me_emcees_prod_testing_5.api.core.http.Headers
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TransactionCreateParamsTest {

    @Test
    fun create() {
        TransactionCreateParams.builder()
            .xTraceId("40c71bbb-c676-4f24-83cf-cc725d7d7a00")
            .addTransaction(
                TransactionCreateParams.Transaction.builder()
                    .amount("123.45")
                    .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                    .description("Vegetables")
                    .type(TransactionTypeProperty.WITHDRAWAL)
                    .billId("112")
                    .billName("Monthly rent")
                    .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .budgetId("4")
                    .budgetName("Groceries")
                    .categoryId("43")
                    .categoryName("Groceries")
                    .currencyCode("EUR")
                    .currencyId("12")
                    .destinationId("2")
                    .destinationName("Buy and Large")
                    .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .externalId("external_id")
                    .externalUrl("external_url")
                    .foreignAmount("123.45")
                    .foreignCurrencyCode("USD")
                    .foreignCurrencyId("17")
                    .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .internalReference("internal_reference")
                    .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .notes("Some example notes")
                    .order(0)
                    .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .piggyBankId(0)
                    .piggyBankName("piggy_bank_name")
                    .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .reconciled(false)
                    .sepaBatchId("sepa_batch_id")
                    .sepaCc("sepa_cc")
                    .sepaCi("sepa_ci")
                    .sepaCountry("sepa_country")
                    .sepaCtId("sepa_ct_id")
                    .sepaCtOp("sepa_ct_op")
                    .sepaDb("sepa_db")
                    .sepaEp("sepa_ep")
                    .sourceId("2")
                    .sourceName("Checking account")
                    .addTag("Barbecue preparation")
                    .build()
            )
            .applyRules(false)
            .errorIfDuplicateHash(false)
            .fireWebhooks(true)
            .groupTitle("Split transaction title.")
            .build()
    }

    @Test
    fun headers() {
        val params =
            TransactionCreateParams.builder()
                .xTraceId("40c71bbb-c676-4f24-83cf-cc725d7d7a00")
                .addTransaction(
                    TransactionCreateParams.Transaction.builder()
                        .amount("123.45")
                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                        .description("Vegetables")
                        .type(TransactionTypeProperty.WITHDRAWAL)
                        .billId("112")
                        .billName("Monthly rent")
                        .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .budgetId("4")
                        .budgetName("Groceries")
                        .categoryId("43")
                        .categoryName("Groceries")
                        .currencyCode("EUR")
                        .currencyId("12")
                        .destinationId("2")
                        .destinationName("Buy and Large")
                        .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalId("external_id")
                        .externalUrl("external_url")
                        .foreignAmount("123.45")
                        .foreignCurrencyCode("USD")
                        .foreignCurrencyId("17")
                        .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .internalReference("internal_reference")
                        .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .notes("Some example notes")
                        .order(0)
                        .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .piggyBankId(0)
                        .piggyBankName("piggy_bank_name")
                        .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .reconciled(false)
                        .sepaBatchId("sepa_batch_id")
                        .sepaCc("sepa_cc")
                        .sepaCi("sepa_ci")
                        .sepaCountry("sepa_country")
                        .sepaCtId("sepa_ct_id")
                        .sepaCtOp("sepa_ct_op")
                        .sepaDb("sepa_db")
                        .sepaEp("sepa_ep")
                        .sourceId("2")
                        .sourceName("Checking account")
                        .addTag("Barbecue preparation")
                        .build()
                )
                .applyRules(false)
                .errorIfDuplicateHash(false)
                .fireWebhooks(true)
                .groupTitle("Split transaction title.")
                .build()

        val headers = params._headers()

        assertThat(headers)
            .isEqualTo(
                Headers.builder().put("X-Trace-Id", "40c71bbb-c676-4f24-83cf-cc725d7d7a00").build()
            )
    }

    @Test
    fun headersWithoutOptionalFields() {
        val params =
            TransactionCreateParams.builder()
                .addTransaction(
                    TransactionCreateParams.Transaction.builder()
                        .amount("123.45")
                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                        .description("Vegetables")
                        .type(TransactionTypeProperty.WITHDRAWAL)
                        .build()
                )
                .build()

        val headers = params._headers()

        assertThat(headers).isEqualTo(Headers.builder().build())
    }

    @Test
    fun body() {
        val params =
            TransactionCreateParams.builder()
                .xTraceId("40c71bbb-c676-4f24-83cf-cc725d7d7a00")
                .addTransaction(
                    TransactionCreateParams.Transaction.builder()
                        .amount("123.45")
                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                        .description("Vegetables")
                        .type(TransactionTypeProperty.WITHDRAWAL)
                        .billId("112")
                        .billName("Monthly rent")
                        .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .budgetId("4")
                        .budgetName("Groceries")
                        .categoryId("43")
                        .categoryName("Groceries")
                        .currencyCode("EUR")
                        .currencyId("12")
                        .destinationId("2")
                        .destinationName("Buy and Large")
                        .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalId("external_id")
                        .externalUrl("external_url")
                        .foreignAmount("123.45")
                        .foreignCurrencyCode("USD")
                        .foreignCurrencyId("17")
                        .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .internalReference("internal_reference")
                        .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .notes("Some example notes")
                        .order(0)
                        .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .piggyBankId(0)
                        .piggyBankName("piggy_bank_name")
                        .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .reconciled(false)
                        .sepaBatchId("sepa_batch_id")
                        .sepaCc("sepa_cc")
                        .sepaCi("sepa_ci")
                        .sepaCountry("sepa_country")
                        .sepaCtId("sepa_ct_id")
                        .sepaCtOp("sepa_ct_op")
                        .sepaDb("sepa_db")
                        .sepaEp("sepa_ep")
                        .sourceId("2")
                        .sourceName("Checking account")
                        .addTag("Barbecue preparation")
                        .build()
                )
                .applyRules(false)
                .errorIfDuplicateHash(false)
                .fireWebhooks(true)
                .groupTitle("Split transaction title.")
                .build()

        val body = params._body()

        assertThat(body.transactions())
            .containsExactly(
                TransactionCreateParams.Transaction.builder()
                    .amount("123.45")
                    .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                    .description("Vegetables")
                    .type(TransactionTypeProperty.WITHDRAWAL)
                    .billId("112")
                    .billName("Monthly rent")
                    .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .budgetId("4")
                    .budgetName("Groceries")
                    .categoryId("43")
                    .categoryName("Groceries")
                    .currencyCode("EUR")
                    .currencyId("12")
                    .destinationId("2")
                    .destinationName("Buy and Large")
                    .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .externalId("external_id")
                    .externalUrl("external_url")
                    .foreignAmount("123.45")
                    .foreignCurrencyCode("USD")
                    .foreignCurrencyId("17")
                    .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .internalReference("internal_reference")
                    .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .notes("Some example notes")
                    .order(0)
                    .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .piggyBankId(0)
                    .piggyBankName("piggy_bank_name")
                    .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .reconciled(false)
                    .sepaBatchId("sepa_batch_id")
                    .sepaCc("sepa_cc")
                    .sepaCi("sepa_ci")
                    .sepaCountry("sepa_country")
                    .sepaCtId("sepa_ct_id")
                    .sepaCtOp("sepa_ct_op")
                    .sepaDb("sepa_db")
                    .sepaEp("sepa_ep")
                    .sourceId("2")
                    .sourceName("Checking account")
                    .addTag("Barbecue preparation")
                    .build()
            )
        assertThat(body.applyRules()).isEqualTo(false)
        assertThat(body.errorIfDuplicateHash()).isEqualTo(false)
        assertThat(body.fireWebhooks()).isEqualTo(true)
        assertThat(body.groupTitle()).isEqualTo("Split transaction title.")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            TransactionCreateParams.builder()
                .addTransaction(
                    TransactionCreateParams.Transaction.builder()
                        .amount("123.45")
                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                        .description("Vegetables")
                        .type(TransactionTypeProperty.WITHDRAWAL)
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.transactions())
            .containsExactly(
                TransactionCreateParams.Transaction.builder()
                    .amount("123.45")
                    .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                    .description("Vegetables")
                    .type(TransactionTypeProperty.WITHDRAWAL)
                    .build()
            )
    }
}
