// File generated from our OpenAPI spec by Stainless.

package com.firefly.api.models.bills

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.firefly.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BillSingleTest {

    @Test
    fun create() {
        val billSingle =
            BillSingle.builder()
                .data(
                    BillRead.builder()
                        .id("2")
                        .attributes(
                            BillRead.Attributes.builder()
                                .active(true)
                                .amountAvg("123.45")
                                .amountMax("123.45")
                                .amountMin("123.45")
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .currencyCode("EUR")
                                .currencyDecimalPlaces(2)
                                .currencyId("5")
                                .currencyName("Euro")
                                .currencySymbol("\$")
                                .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .endDate(OffsetDateTime.parse("2026-04-30T23:59:59+00:00"))
                                .extensionDate(OffsetDateTime.parse("2026-04-30T23:59:59+00:00"))
                                .name("Rent")
                                .nextExpectedMatch(
                                    OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                )
                                .nextExpectedMatchDiff("today")
                                .notes("Some example notes")
                                .objectGroupId("5")
                                .objectGroupOrder(5)
                                .objectGroupTitle("Example Group")
                                .objectHasCurrencySetting(true)
                                .order(1)
                                .addPaidDate(
                                    BillRead.Attributes.PaidDate.builder()
                                        .amount("123.45")
                                        .currencyCode("EUR")
                                        .currencyDecimalPlaces(2)
                                        .currencyId("5")
                                        .currencyName("Euro")
                                        .currencySymbol("\$")
                                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                        .foreignAmount("123.45")
                                        .pcAmount("123.45")
                                        .pcForeignAmount("123.45")
                                        .primaryCurrencyCode("EUR")
                                        .primaryCurrencyDecimalPlaces(2)
                                        .primaryCurrencyId("5")
                                        .primaryCurrencyName("Euro")
                                        .primaryCurrencySymbol("\$")
                                        .subscriptionId("123")
                                        .transactionGroupId("123")
                                        .transactionJournalId("123")
                                        .build()
                                )
                                .addPayDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .pcAmountAvg("123.45")
                                .pcAmountMax("123.45")
                                .pcAmountMin("123.45")
                                .primaryCurrencyCode("EUR")
                                .primaryCurrencyDecimalPlaces(2)
                                .primaryCurrencyId("5")
                                .primaryCurrencyName("Euro")
                                .primaryCurrencySymbol("\$")
                                .repeatFreq(BillRepeatFrequency.MONTHLY)
                                .skip(0)
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .build()
                        )
                        .type("bills")
                        .build()
                )
                .build()

        assertThat(billSingle.data())
            .isEqualTo(
                BillRead.builder()
                    .id("2")
                    .attributes(
                        BillRead.Attributes.builder()
                            .active(true)
                            .amountAvg("123.45")
                            .amountMax("123.45")
                            .amountMin("123.45")
                            .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .currencyCode("EUR")
                            .currencyDecimalPlaces(2)
                            .currencyId("5")
                            .currencyName("Euro")
                            .currencySymbol("\$")
                            .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .endDate(OffsetDateTime.parse("2026-04-30T23:59:59+00:00"))
                            .extensionDate(OffsetDateTime.parse("2026-04-30T23:59:59+00:00"))
                            .name("Rent")
                            .nextExpectedMatch(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .nextExpectedMatchDiff("today")
                            .notes("Some example notes")
                            .objectGroupId("5")
                            .objectGroupOrder(5)
                            .objectGroupTitle("Example Group")
                            .objectHasCurrencySetting(true)
                            .order(1)
                            .addPaidDate(
                                BillRead.Attributes.PaidDate.builder()
                                    .amount("123.45")
                                    .currencyCode("EUR")
                                    .currencyDecimalPlaces(2)
                                    .currencyId("5")
                                    .currencyName("Euro")
                                    .currencySymbol("\$")
                                    .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                    .foreignAmount("123.45")
                                    .pcAmount("123.45")
                                    .pcForeignAmount("123.45")
                                    .primaryCurrencyCode("EUR")
                                    .primaryCurrencyDecimalPlaces(2)
                                    .primaryCurrencyId("5")
                                    .primaryCurrencyName("Euro")
                                    .primaryCurrencySymbol("\$")
                                    .subscriptionId("123")
                                    .transactionGroupId("123")
                                    .transactionJournalId("123")
                                    .build()
                            )
                            .addPayDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .pcAmountAvg("123.45")
                            .pcAmountMax("123.45")
                            .pcAmountMin("123.45")
                            .primaryCurrencyCode("EUR")
                            .primaryCurrencyDecimalPlaces(2)
                            .primaryCurrencyId("5")
                            .primaryCurrencyName("Euro")
                            .primaryCurrencySymbol("\$")
                            .repeatFreq(BillRepeatFrequency.MONTHLY)
                            .skip(0)
                            .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .build()
                    )
                    .type("bills")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val billSingle =
            BillSingle.builder()
                .data(
                    BillRead.builder()
                        .id("2")
                        .attributes(
                            BillRead.Attributes.builder()
                                .active(true)
                                .amountAvg("123.45")
                                .amountMax("123.45")
                                .amountMin("123.45")
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .currencyCode("EUR")
                                .currencyDecimalPlaces(2)
                                .currencyId("5")
                                .currencyName("Euro")
                                .currencySymbol("\$")
                                .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .endDate(OffsetDateTime.parse("2026-04-30T23:59:59+00:00"))
                                .extensionDate(OffsetDateTime.parse("2026-04-30T23:59:59+00:00"))
                                .name("Rent")
                                .nextExpectedMatch(
                                    OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                )
                                .nextExpectedMatchDiff("today")
                                .notes("Some example notes")
                                .objectGroupId("5")
                                .objectGroupOrder(5)
                                .objectGroupTitle("Example Group")
                                .objectHasCurrencySetting(true)
                                .order(1)
                                .addPaidDate(
                                    BillRead.Attributes.PaidDate.builder()
                                        .amount("123.45")
                                        .currencyCode("EUR")
                                        .currencyDecimalPlaces(2)
                                        .currencyId("5")
                                        .currencyName("Euro")
                                        .currencySymbol("\$")
                                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                        .foreignAmount("123.45")
                                        .pcAmount("123.45")
                                        .pcForeignAmount("123.45")
                                        .primaryCurrencyCode("EUR")
                                        .primaryCurrencyDecimalPlaces(2)
                                        .primaryCurrencyId("5")
                                        .primaryCurrencyName("Euro")
                                        .primaryCurrencySymbol("\$")
                                        .subscriptionId("123")
                                        .transactionGroupId("123")
                                        .transactionJournalId("123")
                                        .build()
                                )
                                .addPayDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .pcAmountAvg("123.45")
                                .pcAmountMax("123.45")
                                .pcAmountMin("123.45")
                                .primaryCurrencyCode("EUR")
                                .primaryCurrencyDecimalPlaces(2)
                                .primaryCurrencyId("5")
                                .primaryCurrencyName("Euro")
                                .primaryCurrencySymbol("\$")
                                .repeatFreq(BillRepeatFrequency.MONTHLY)
                                .skip(0)
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .build()
                        )
                        .type("bills")
                        .build()
                )
                .build()

        val roundtrippedBillSingle =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(billSingle),
                jacksonTypeRef<BillSingle>(),
            )

        assertThat(roundtrippedBillSingle).isEqualTo(billSingle)
    }
}
