// File generated from our OpenAPI spec by Stainless.

package com.firefly.api.models.transactions

import com.firefly.api.core.http.Headers
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TransactionUpdateParamsTest {

    @Test
    fun create() {
        TransactionUpdateParams.builder()
            .id("123")
            .xTraceId("40c71bbb-c676-4f24-83cf-cc725d7d7a00")
            .applyRules(false)
            .fireWebhooks(true)
            .groupTitle("Split transaction title.")
            .addTransaction(
                TransactionUpdateParams.Transaction.builder()
                    .amount("123.45")
                    .billId("111")
                    .billName("Monthly rent")
                    .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .budgetId("4")
                    .categoryId("43")
                    .categoryName("Groceries")
                    .currencyCode("EUR")
                    .currencyId("12")
                    .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                    .description("Vegetables")
                    .destinationIban("NL02ABNA0123456789")
                    .destinationId("2")
                    .destinationName("Buy and Large")
                    .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .externalId("external_id")
                    .externalUrl("external_url")
                    .foreignAmount("123.45")
                    .foreignCurrencyCode("USD")
                    .foreignCurrencyId("17")
                    .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .internalReference("internal_reference")
                    .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .notes("Some example notes")
                    .order(0)
                    .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .reconciled(false)
                    .sepaBatchId("sepa_batch_id")
                    .sepaCc("sepa_cc")
                    .sepaCi("sepa_ci")
                    .sepaCountry("sepa_country")
                    .sepaCtId("sepa_ct_id")
                    .sepaCtOp("sepa_ct_op")
                    .sepaDb("sepa_db")
                    .sepaEp("sepa_ep")
                    .sourceIban("NL02ABNA0123456789")
                    .sourceId("2")
                    .sourceName("Checking account")
                    .addTag("Barbecue preparation")
                    .transactionJournalId("123")
                    .type(TransactionTypeProperty.WITHDRAWAL)
                    .build()
            )
            .build()
    }

    @Test
    fun pathParams() {
        val params = TransactionUpdateParams.builder().id("123").build()

        assertThat(params._pathParam(0)).isEqualTo("123")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun headers() {
        val params =
            TransactionUpdateParams.builder()
                .id("123")
                .xTraceId("40c71bbb-c676-4f24-83cf-cc725d7d7a00")
                .applyRules(false)
                .fireWebhooks(true)
                .groupTitle("Split transaction title.")
                .addTransaction(
                    TransactionUpdateParams.Transaction.builder()
                        .amount("123.45")
                        .billId("111")
                        .billName("Monthly rent")
                        .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .budgetId("4")
                        .categoryId("43")
                        .categoryName("Groceries")
                        .currencyCode("EUR")
                        .currencyId("12")
                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                        .description("Vegetables")
                        .destinationIban("NL02ABNA0123456789")
                        .destinationId("2")
                        .destinationName("Buy and Large")
                        .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalId("external_id")
                        .externalUrl("external_url")
                        .foreignAmount("123.45")
                        .foreignCurrencyCode("USD")
                        .foreignCurrencyId("17")
                        .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .internalReference("internal_reference")
                        .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .notes("Some example notes")
                        .order(0)
                        .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .reconciled(false)
                        .sepaBatchId("sepa_batch_id")
                        .sepaCc("sepa_cc")
                        .sepaCi("sepa_ci")
                        .sepaCountry("sepa_country")
                        .sepaCtId("sepa_ct_id")
                        .sepaCtOp("sepa_ct_op")
                        .sepaDb("sepa_db")
                        .sepaEp("sepa_ep")
                        .sourceIban("NL02ABNA0123456789")
                        .sourceId("2")
                        .sourceName("Checking account")
                        .addTag("Barbecue preparation")
                        .transactionJournalId("123")
                        .type(TransactionTypeProperty.WITHDRAWAL)
                        .build()
                )
                .build()

        val headers = params._headers()

        assertThat(headers)
            .isEqualTo(
                Headers.builder().put("X-Trace-Id", "40c71bbb-c676-4f24-83cf-cc725d7d7a00").build()
            )
    }

    @Test
    fun headersWithoutOptionalFields() {
        val params = TransactionUpdateParams.builder().id("123").build()

        val headers = params._headers()

        assertThat(headers).isEqualTo(Headers.builder().build())
    }

    @Test
    fun body() {
        val params =
            TransactionUpdateParams.builder()
                .id("123")
                .xTraceId("40c71bbb-c676-4f24-83cf-cc725d7d7a00")
                .applyRules(false)
                .fireWebhooks(true)
                .groupTitle("Split transaction title.")
                .addTransaction(
                    TransactionUpdateParams.Transaction.builder()
                        .amount("123.45")
                        .billId("111")
                        .billName("Monthly rent")
                        .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .budgetId("4")
                        .categoryId("43")
                        .categoryName("Groceries")
                        .currencyCode("EUR")
                        .currencyId("12")
                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                        .description("Vegetables")
                        .destinationIban("NL02ABNA0123456789")
                        .destinationId("2")
                        .destinationName("Buy and Large")
                        .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalId("external_id")
                        .externalUrl("external_url")
                        .foreignAmount("123.45")
                        .foreignCurrencyCode("USD")
                        .foreignCurrencyId("17")
                        .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .internalReference("internal_reference")
                        .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .notes("Some example notes")
                        .order(0)
                        .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .reconciled(false)
                        .sepaBatchId("sepa_batch_id")
                        .sepaCc("sepa_cc")
                        .sepaCi("sepa_ci")
                        .sepaCountry("sepa_country")
                        .sepaCtId("sepa_ct_id")
                        .sepaCtOp("sepa_ct_op")
                        .sepaDb("sepa_db")
                        .sepaEp("sepa_ep")
                        .sourceIban("NL02ABNA0123456789")
                        .sourceId("2")
                        .sourceName("Checking account")
                        .addTag("Barbecue preparation")
                        .transactionJournalId("123")
                        .type(TransactionTypeProperty.WITHDRAWAL)
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.applyRules()).isEqualTo(false)
        assertThat(body.fireWebhooks()).isEqualTo(true)
        assertThat(body.groupTitle()).isEqualTo("Split transaction title.")
        assertThat(body.transactions())
            .containsExactly(
                TransactionUpdateParams.Transaction.builder()
                    .amount("123.45")
                    .billId("111")
                    .billName("Monthly rent")
                    .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .budgetId("4")
                    .categoryId("43")
                    .categoryName("Groceries")
                    .currencyCode("EUR")
                    .currencyId("12")
                    .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                    .description("Vegetables")
                    .destinationIban("NL02ABNA0123456789")
                    .destinationId("2")
                    .destinationName("Buy and Large")
                    .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .externalId("external_id")
                    .externalUrl("external_url")
                    .foreignAmount("123.45")
                    .foreignCurrencyCode("USD")
                    .foreignCurrencyId("17")
                    .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .internalReference("internal_reference")
                    .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .notes("Some example notes")
                    .order(0)
                    .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .reconciled(false)
                    .sepaBatchId("sepa_batch_id")
                    .sepaCc("sepa_cc")
                    .sepaCi("sepa_ci")
                    .sepaCountry("sepa_country")
                    .sepaCtId("sepa_ct_id")
                    .sepaCtOp("sepa_ct_op")
                    .sepaDb("sepa_db")
                    .sepaEp("sepa_ep")
                    .sourceIban("NL02ABNA0123456789")
                    .sourceId("2")
                    .sourceName("Checking account")
                    .addTag("Barbecue preparation")
                    .transactionJournalId("123")
                    .type(TransactionTypeProperty.WITHDRAWAL)
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = TransactionUpdateParams.builder().id("123").build()

        val body = params._body()
    }
}
