// File generated from our OpenAPI spec by Stainless.

package com.configure_me_emcees_prod_testing_5.api.models.recurrences

import com.configure_me_emcees_prod_testing_5.api.core.jsonMapper
import com.configure_me_emcees_prod_testing_5.api.models.attachments.ObjectLink
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RecurrenceSingleTest {

    @Test
    fun create() {
        val recurrenceSingle =
            RecurrenceSingle.builder()
                .data(
                    RecurrenceRead.builder()
                        .id("2")
                        .attributes(
                            RecurrenceRead.Attributes.builder()
                                .active(true)
                                .applyRules(true)
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .description("Recurring transaction for the monthly rent")
                                .firstDate(LocalDate.parse("2026-04-30"))
                                .latestDate(LocalDate.parse("2026-04-01"))
                                .notes("Some notes")
                                .nrOfRepetitions(5)
                                .repeatUntil(LocalDate.parse("2026-04-30"))
                                .addRepetition(
                                    RecurrenceRead.Attributes.Repetition.builder()
                                        .moment("3")
                                        .type(RecurrenceRepetitionType.WEEKLY)
                                        .id("2")
                                        .createdAt(
                                            OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                        )
                                        .description("Every week on Friday")
                                        .addOccurrence(
                                            OffsetDateTime.parse("2026-04-30T23:59:59+00:00")
                                        )
                                        .skip(0)
                                        .updatedAt(
                                            OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                        )
                                        .weekend(1)
                                        .build()
                                )
                                .title("Rent")
                                .addTransaction(
                                    RecurrenceRead.Attributes.Transaction.builder()
                                        .amount("123.45")
                                        .description("Rent for the current month")
                                        .id(
                                            "ID of the recurring transaction. Not to be confused with the ID of the recurrence itself."
                                        )
                                        .budgetId("4")
                                        .budgetName("Groceries")
                                        .categoryId("211")
                                        .categoryName("Bills")
                                        .currencyCode("EUR")
                                        .currencyDecimalPlaces(2)
                                        .currencyId("5")
                                        .currencyName("Euro")
                                        .currencySymbol("\$")
                                        .destinationIban("NL02ABNA0123456789")
                                        .destinationId("258")
                                        .destinationName("Buy and Large")
                                        .destinationType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .foreignAmount("123.45")
                                        .foreignCurrencyCode("GBP")
                                        .foreignCurrencyDecimalPlaces(2)
                                        .foreignCurrencyId("17")
                                        .foreignCurrencyName("British Pound")
                                        .foreignCurrencySymbol("\$")
                                        .objectHasCurrencySetting(true)
                                        .pcAmount("123.45")
                                        .pcForeignAmount("123.45")
                                        .piggyBankId("123")
                                        .piggyBankName("piggy_bank_name")
                                        .primaryCurrencyCode("EUR")
                                        .primaryCurrencyDecimalPlaces(2)
                                        .primaryCurrencyId("5")
                                        .primaryCurrencyName("Euro")
                                        .primaryCurrencySymbol("\$")
                                        .sourceIban("NL02ABNA0123456789")
                                        .sourceId("913")
                                        .sourceName("Checking account")
                                        .sourceType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .subscriptionId("123")
                                        .subscriptionName("subscription_name")
                                        .addTag("Barbecue preparation")
                                        .build()
                                )
                                .type(RecurrenceTransactionType.WITHDRAWAL)
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .build()
                        )
                        .links(
                            ObjectLink.builder()
                                ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                                .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                                .build()
                        )
                        .type("recurrences")
                        .build()
                )
                .build()

        assertThat(recurrenceSingle.data())
            .isEqualTo(
                RecurrenceRead.builder()
                    .id("2")
                    .attributes(
                        RecurrenceRead.Attributes.builder()
                            .active(true)
                            .applyRules(true)
                            .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .description("Recurring transaction for the monthly rent")
                            .firstDate(LocalDate.parse("2026-04-30"))
                            .latestDate(LocalDate.parse("2026-04-01"))
                            .notes("Some notes")
                            .nrOfRepetitions(5)
                            .repeatUntil(LocalDate.parse("2026-04-30"))
                            .addRepetition(
                                RecurrenceRead.Attributes.Repetition.builder()
                                    .moment("3")
                                    .type(RecurrenceRepetitionType.WEEKLY)
                                    .id("2")
                                    .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                    .description("Every week on Friday")
                                    .addOccurrence(
                                        OffsetDateTime.parse("2026-04-30T23:59:59+00:00")
                                    )
                                    .skip(0)
                                    .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                    .weekend(1)
                                    .build()
                            )
                            .title("Rent")
                            .addTransaction(
                                RecurrenceRead.Attributes.Transaction.builder()
                                    .amount("123.45")
                                    .description("Rent for the current month")
                                    .id(
                                        "ID of the recurring transaction. Not to be confused with the ID of the recurrence itself."
                                    )
                                    .budgetId("4")
                                    .budgetName("Groceries")
                                    .categoryId("211")
                                    .categoryName("Bills")
                                    .currencyCode("EUR")
                                    .currencyDecimalPlaces(2)
                                    .currencyId("5")
                                    .currencyName("Euro")
                                    .currencySymbol("\$")
                                    .destinationIban("NL02ABNA0123456789")
                                    .destinationId("258")
                                    .destinationName("Buy and Large")
                                    .destinationType(AccountTypeProperty.ASSET_ACCOUNT)
                                    .foreignAmount("123.45")
                                    .foreignCurrencyCode("GBP")
                                    .foreignCurrencyDecimalPlaces(2)
                                    .foreignCurrencyId("17")
                                    .foreignCurrencyName("British Pound")
                                    .foreignCurrencySymbol("\$")
                                    .objectHasCurrencySetting(true)
                                    .pcAmount("123.45")
                                    .pcForeignAmount("123.45")
                                    .piggyBankId("123")
                                    .piggyBankName("piggy_bank_name")
                                    .primaryCurrencyCode("EUR")
                                    .primaryCurrencyDecimalPlaces(2)
                                    .primaryCurrencyId("5")
                                    .primaryCurrencyName("Euro")
                                    .primaryCurrencySymbol("\$")
                                    .sourceIban("NL02ABNA0123456789")
                                    .sourceId("913")
                                    .sourceName("Checking account")
                                    .sourceType(AccountTypeProperty.ASSET_ACCOUNT)
                                    .subscriptionId("123")
                                    .subscriptionName("subscription_name")
                                    .addTag("Barbecue preparation")
                                    .build()
                            )
                            .type(RecurrenceTransactionType.WITHDRAWAL)
                            .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .build()
                    )
                    .links(
                        ObjectLink.builder()
                            ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                            .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                            .build()
                    )
                    .type("recurrences")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val recurrenceSingle =
            RecurrenceSingle.builder()
                .data(
                    RecurrenceRead.builder()
                        .id("2")
                        .attributes(
                            RecurrenceRead.Attributes.builder()
                                .active(true)
                                .applyRules(true)
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .description("Recurring transaction for the monthly rent")
                                .firstDate(LocalDate.parse("2026-04-30"))
                                .latestDate(LocalDate.parse("2026-04-01"))
                                .notes("Some notes")
                                .nrOfRepetitions(5)
                                .repeatUntil(LocalDate.parse("2026-04-30"))
                                .addRepetition(
                                    RecurrenceRead.Attributes.Repetition.builder()
                                        .moment("3")
                                        .type(RecurrenceRepetitionType.WEEKLY)
                                        .id("2")
                                        .createdAt(
                                            OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                        )
                                        .description("Every week on Friday")
                                        .addOccurrence(
                                            OffsetDateTime.parse("2026-04-30T23:59:59+00:00")
                                        )
                                        .skip(0)
                                        .updatedAt(
                                            OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                        )
                                        .weekend(1)
                                        .build()
                                )
                                .title("Rent")
                                .addTransaction(
                                    RecurrenceRead.Attributes.Transaction.builder()
                                        .amount("123.45")
                                        .description("Rent for the current month")
                                        .id(
                                            "ID of the recurring transaction. Not to be confused with the ID of the recurrence itself."
                                        )
                                        .budgetId("4")
                                        .budgetName("Groceries")
                                        .categoryId("211")
                                        .categoryName("Bills")
                                        .currencyCode("EUR")
                                        .currencyDecimalPlaces(2)
                                        .currencyId("5")
                                        .currencyName("Euro")
                                        .currencySymbol("\$")
                                        .destinationIban("NL02ABNA0123456789")
                                        .destinationId("258")
                                        .destinationName("Buy and Large")
                                        .destinationType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .foreignAmount("123.45")
                                        .foreignCurrencyCode("GBP")
                                        .foreignCurrencyDecimalPlaces(2)
                                        .foreignCurrencyId("17")
                                        .foreignCurrencyName("British Pound")
                                        .foreignCurrencySymbol("\$")
                                        .objectHasCurrencySetting(true)
                                        .pcAmount("123.45")
                                        .pcForeignAmount("123.45")
                                        .piggyBankId("123")
                                        .piggyBankName("piggy_bank_name")
                                        .primaryCurrencyCode("EUR")
                                        .primaryCurrencyDecimalPlaces(2)
                                        .primaryCurrencyId("5")
                                        .primaryCurrencyName("Euro")
                                        .primaryCurrencySymbol("\$")
                                        .sourceIban("NL02ABNA0123456789")
                                        .sourceId("913")
                                        .sourceName("Checking account")
                                        .sourceType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .subscriptionId("123")
                                        .subscriptionName("subscription_name")
                                        .addTag("Barbecue preparation")
                                        .build()
                                )
                                .type(RecurrenceTransactionType.WITHDRAWAL)
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .build()
                        )
                        .links(
                            ObjectLink.builder()
                                ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                                .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                                .build()
                        )
                        .type("recurrences")
                        .build()
                )
                .build()

        val roundtrippedRecurrenceSingle =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(recurrenceSingle),
                jacksonTypeRef<RecurrenceSingle>(),
            )

        assertThat(roundtrippedRecurrenceSingle).isEqualTo(recurrenceSingle)
    }
}
