// File generated from our OpenAPI spec by Stainless.

package com.firefly.api.models.accounts

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.firefly.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AccountArrayTest {

    @Test
    fun create() {
        val accountArray =
            AccountArray.builder()
                .addData(
                    AccountRead.builder()
                        .id("2")
                        .attributes(
                            AccountRead.Attributes.builder()
                                .name("My checking account")
                                .type(ShortAccountTypeProperty.ASSET)
                                .accountNumber("7009312345678")
                                .accountRole(AccountRoleProperty.DEFAULT_ASSET)
                                .active(false)
                                .balanceDifference("123.45")
                                .bic("BOFAUS3N")
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .creditCardType(CreditCardTypeProperty.MONTHLY_FULL)
                                .currencyCode("EUR")
                                .currencyDecimalPlaces(2)
                                .currencyId("5")
                                .currencyName("Euro")
                                .currencySymbol("\$")
                                .currentBalance("123.45")
                                .currentBalanceDate(
                                    OffsetDateTime.parse("2026-04-30T23:59:59+00:00")
                                )
                                .debtAmount("1012.12")
                                .iban("GB98MIDL07009312345678")
                                .includeNetWorth(true)
                                .interest("5.3")
                                .interestPeriod(InterestPeriodProperty.MONTHLY)
                                .lastActivity(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .latitude(51.983333)
                                .liabilityDirection(LiabilityDirectionProperty.CREDIT)
                                .liabilityType(LiabilityTypeProperty.LOAN)
                                .longitude(5.916667)
                                .monthlyPaymentDate(
                                    OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                )
                                .notes("Some example notes")
                                .objectGroupId("5")
                                .objectGroupOrder(5)
                                .objectGroupTitle("Example Group")
                                .objectHasCurrencySetting(true)
                                .openingBalance("-1012.12")
                                .openingBalanceDate(
                                    OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                )
                                .order(1)
                                .pcBalanceDifference("123.45")
                                .pcCurrentBalance("123.45")
                                .pcDebtAmount("1012.12")
                                .pcOpeningBalance("-1012.12")
                                .pcVirtualBalance("123.45")
                                .primaryCurrencyCode("EUR")
                                .primaryCurrencyDecimalPlaces(2)
                                .primaryCurrencyId("5")
                                .primaryCurrencyName("Euro")
                                .primaryCurrencySymbol("\$")
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .virtualBalance("123.45")
                                .zoomLevel(6)
                                .build()
                        )
                        .type("accounts")
                        .build()
                )
                .meta(
                    Meta.builder()
                        .pagination(
                            Meta.Pagination.builder()
                                .count(20L)
                                .currentPage(1L)
                                .perPage(100L)
                                .total(3L)
                                .totalPages(1L)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(accountArray.data())
            .containsExactly(
                AccountRead.builder()
                    .id("2")
                    .attributes(
                        AccountRead.Attributes.builder()
                            .name("My checking account")
                            .type(ShortAccountTypeProperty.ASSET)
                            .accountNumber("7009312345678")
                            .accountRole(AccountRoleProperty.DEFAULT_ASSET)
                            .active(false)
                            .balanceDifference("123.45")
                            .bic("BOFAUS3N")
                            .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .creditCardType(CreditCardTypeProperty.MONTHLY_FULL)
                            .currencyCode("EUR")
                            .currencyDecimalPlaces(2)
                            .currencyId("5")
                            .currencyName("Euro")
                            .currencySymbol("\$")
                            .currentBalance("123.45")
                            .currentBalanceDate(OffsetDateTime.parse("2026-04-30T23:59:59+00:00"))
                            .debtAmount("1012.12")
                            .iban("GB98MIDL07009312345678")
                            .includeNetWorth(true)
                            .interest("5.3")
                            .interestPeriod(InterestPeriodProperty.MONTHLY)
                            .lastActivity(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .latitude(51.983333)
                            .liabilityDirection(LiabilityDirectionProperty.CREDIT)
                            .liabilityType(LiabilityTypeProperty.LOAN)
                            .longitude(5.916667)
                            .monthlyPaymentDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .notes("Some example notes")
                            .objectGroupId("5")
                            .objectGroupOrder(5)
                            .objectGroupTitle("Example Group")
                            .objectHasCurrencySetting(true)
                            .openingBalance("-1012.12")
                            .openingBalanceDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .order(1)
                            .pcBalanceDifference("123.45")
                            .pcCurrentBalance("123.45")
                            .pcDebtAmount("1012.12")
                            .pcOpeningBalance("-1012.12")
                            .pcVirtualBalance("123.45")
                            .primaryCurrencyCode("EUR")
                            .primaryCurrencyDecimalPlaces(2)
                            .primaryCurrencyId("5")
                            .primaryCurrencyName("Euro")
                            .primaryCurrencySymbol("\$")
                            .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .virtualBalance("123.45")
                            .zoomLevel(6)
                            .build()
                    )
                    .type("accounts")
                    .build()
            )
        assertThat(accountArray.meta())
            .isEqualTo(
                Meta.builder()
                    .pagination(
                        Meta.Pagination.builder()
                            .count(20L)
                            .currentPage(1L)
                            .perPage(100L)
                            .total(3L)
                            .totalPages(1L)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val accountArray =
            AccountArray.builder()
                .addData(
                    AccountRead.builder()
                        .id("2")
                        .attributes(
                            AccountRead.Attributes.builder()
                                .name("My checking account")
                                .type(ShortAccountTypeProperty.ASSET)
                                .accountNumber("7009312345678")
                                .accountRole(AccountRoleProperty.DEFAULT_ASSET)
                                .active(false)
                                .balanceDifference("123.45")
                                .bic("BOFAUS3N")
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .creditCardType(CreditCardTypeProperty.MONTHLY_FULL)
                                .currencyCode("EUR")
                                .currencyDecimalPlaces(2)
                                .currencyId("5")
                                .currencyName("Euro")
                                .currencySymbol("\$")
                                .currentBalance("123.45")
                                .currentBalanceDate(
                                    OffsetDateTime.parse("2026-04-30T23:59:59+00:00")
                                )
                                .debtAmount("1012.12")
                                .iban("GB98MIDL07009312345678")
                                .includeNetWorth(true)
                                .interest("5.3")
                                .interestPeriod(InterestPeriodProperty.MONTHLY)
                                .lastActivity(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .latitude(51.983333)
                                .liabilityDirection(LiabilityDirectionProperty.CREDIT)
                                .liabilityType(LiabilityTypeProperty.LOAN)
                                .longitude(5.916667)
                                .monthlyPaymentDate(
                                    OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                )
                                .notes("Some example notes")
                                .objectGroupId("5")
                                .objectGroupOrder(5)
                                .objectGroupTitle("Example Group")
                                .objectHasCurrencySetting(true)
                                .openingBalance("-1012.12")
                                .openingBalanceDate(
                                    OffsetDateTime.parse("2026-04-01T00:00:00+00:00")
                                )
                                .order(1)
                                .pcBalanceDifference("123.45")
                                .pcCurrentBalance("123.45")
                                .pcDebtAmount("1012.12")
                                .pcOpeningBalance("-1012.12")
                                .pcVirtualBalance("123.45")
                                .primaryCurrencyCode("EUR")
                                .primaryCurrencyDecimalPlaces(2)
                                .primaryCurrencyId("5")
                                .primaryCurrencyName("Euro")
                                .primaryCurrencySymbol("\$")
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .virtualBalance("123.45")
                                .zoomLevel(6)
                                .build()
                        )
                        .type("accounts")
                        .build()
                )
                .meta(
                    Meta.builder()
                        .pagination(
                            Meta.Pagination.builder()
                                .count(20L)
                                .currentPage(1L)
                                .perPage(100L)
                                .total(3L)
                                .totalPages(1L)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedAccountArray =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(accountArray),
                jacksonTypeRef<AccountArray>(),
            )

        assertThat(roundtrippedAccountArray).isEqualTo(accountArray)
    }
}
