// File generated from our OpenAPI spec by Stainless.

package com.firefly.api.models.accounts

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.firefly.api.core.JsonValue
import com.firefly.api.core.jsonMapper
import com.firefly.api.models.attachments.ObjectLink
import com.firefly.api.models.piggybanks.PiggyBankRead
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PiggyBankArrayTest {

    @Test
    fun create() {
        val piggyBankArray =
            PiggyBankArray.builder()
                .addData(
                    PiggyBankRead.builder()
                        .id("2")
                        .attributes(
                            PiggyBankRead.Attributes.builder()
                                .accountId(JsonValue.from(mapOf<String, Any>()))
                                .name("New digital camera")
                                .targetAmount("123.45")
                                .addAccount(
                                    PiggyBankRead.Attributes.Account.builder()
                                        .accountId("3")
                                        .currentAmount("123.45")
                                        .name("Checking account")
                                        .pcCurrentAmount("123.45")
                                        .build()
                                )
                                .active(true)
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .currencyCode("EUR")
                                .currencyDecimalPlaces(2)
                                .currencyId("5")
                                .currencyName("Euro")
                                .currencySymbol("\$")
                                .currentAmount("123.45")
                                .leftToSave("700.00")
                                .notes("Some notes")
                                .objectGroupId("5")
                                .objectGroupOrder(5)
                                .objectGroupTitle("Example Group")
                                .objectHasCurrencySetting(true)
                                .order(5)
                                .pcCurrentAmount("123.45")
                                .pcLeftToSave("700.00")
                                .pcSavePerMonth("12.45")
                                .pcTargetAmount("123.45")
                                .percentage(12)
                                .primaryCurrencyCode("EUR")
                                .primaryCurrencyDecimalPlaces(2)
                                .primaryCurrencyId("5")
                                .primaryCurrencyName("Euro")
                                .primaryCurrencySymbol("\$")
                                .savePerMonth("12.45")
                                .startDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .targetDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .build()
                        )
                        .links(
                            ObjectLink.builder()
                                ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                                .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                                .build()
                        )
                        .type("piggy_banks")
                        .build()
                )
                .links(
                    PageLink.builder()
                        .first("https://demo.firefly-iii.org/api/v1/OBJECT?&page=1")
                        .last("https://demo.firefly-iii.org/api/v1/OBJECT?&page=12")
                        .next("https://demo.firefly-iii.org/api/v1/OBJECT?&page=3")
                        .prev("https://demo.firefly-iii.org/api/v1/OBJECT?&page=2")
                        .self("https://demo.firefly-iii.org/api/v1/OBJECT?&page=4")
                        .build()
                )
                .meta(
                    Meta.builder()
                        .pagination(
                            Meta.Pagination.builder()
                                .count(20L)
                                .currentPage(1L)
                                .perPage(100L)
                                .total(3L)
                                .totalPages(1L)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(piggyBankArray.data())
            .containsExactly(
                PiggyBankRead.builder()
                    .id("2")
                    .attributes(
                        PiggyBankRead.Attributes.builder()
                            .accountId(JsonValue.from(mapOf<String, Any>()))
                            .name("New digital camera")
                            .targetAmount("123.45")
                            .addAccount(
                                PiggyBankRead.Attributes.Account.builder()
                                    .accountId("3")
                                    .currentAmount("123.45")
                                    .name("Checking account")
                                    .pcCurrentAmount("123.45")
                                    .build()
                            )
                            .active(true)
                            .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .currencyCode("EUR")
                            .currencyDecimalPlaces(2)
                            .currencyId("5")
                            .currencyName("Euro")
                            .currencySymbol("\$")
                            .currentAmount("123.45")
                            .leftToSave("700.00")
                            .notes("Some notes")
                            .objectGroupId("5")
                            .objectGroupOrder(5)
                            .objectGroupTitle("Example Group")
                            .objectHasCurrencySetting(true)
                            .order(5)
                            .pcCurrentAmount("123.45")
                            .pcLeftToSave("700.00")
                            .pcSavePerMonth("12.45")
                            .pcTargetAmount("123.45")
                            .percentage(12)
                            .primaryCurrencyCode("EUR")
                            .primaryCurrencyDecimalPlaces(2)
                            .primaryCurrencyId("5")
                            .primaryCurrencyName("Euro")
                            .primaryCurrencySymbol("\$")
                            .savePerMonth("12.45")
                            .startDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .targetDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .build()
                    )
                    .links(
                        ObjectLink.builder()
                            ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                            .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                            .build()
                    )
                    .type("piggy_banks")
                    .build()
            )
        assertThat(piggyBankArray.links())
            .isEqualTo(
                PageLink.builder()
                    .first("https://demo.firefly-iii.org/api/v1/OBJECT?&page=1")
                    .last("https://demo.firefly-iii.org/api/v1/OBJECT?&page=12")
                    .next("https://demo.firefly-iii.org/api/v1/OBJECT?&page=3")
                    .prev("https://demo.firefly-iii.org/api/v1/OBJECT?&page=2")
                    .self("https://demo.firefly-iii.org/api/v1/OBJECT?&page=4")
                    .build()
            )
        assertThat(piggyBankArray.meta())
            .isEqualTo(
                Meta.builder()
                    .pagination(
                        Meta.Pagination.builder()
                            .count(20L)
                            .currentPage(1L)
                            .perPage(100L)
                            .total(3L)
                            .totalPages(1L)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val piggyBankArray =
            PiggyBankArray.builder()
                .addData(
                    PiggyBankRead.builder()
                        .id("2")
                        .attributes(
                            PiggyBankRead.Attributes.builder()
                                .accountId(JsonValue.from(mapOf<String, Any>()))
                                .name("New digital camera")
                                .targetAmount("123.45")
                                .addAccount(
                                    PiggyBankRead.Attributes.Account.builder()
                                        .accountId("3")
                                        .currentAmount("123.45")
                                        .name("Checking account")
                                        .pcCurrentAmount("123.45")
                                        .build()
                                )
                                .active(true)
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .currencyCode("EUR")
                                .currencyDecimalPlaces(2)
                                .currencyId("5")
                                .currencyName("Euro")
                                .currencySymbol("\$")
                                .currentAmount("123.45")
                                .leftToSave("700.00")
                                .notes("Some notes")
                                .objectGroupId("5")
                                .objectGroupOrder(5)
                                .objectGroupTitle("Example Group")
                                .objectHasCurrencySetting(true)
                                .order(5)
                                .pcCurrentAmount("123.45")
                                .pcLeftToSave("700.00")
                                .pcSavePerMonth("12.45")
                                .pcTargetAmount("123.45")
                                .percentage(12)
                                .primaryCurrencyCode("EUR")
                                .primaryCurrencyDecimalPlaces(2)
                                .primaryCurrencyId("5")
                                .primaryCurrencyName("Euro")
                                .primaryCurrencySymbol("\$")
                                .savePerMonth("12.45")
                                .startDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .targetDate(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .build()
                        )
                        .links(
                            ObjectLink.builder()
                                ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                                .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                                .build()
                        )
                        .type("piggy_banks")
                        .build()
                )
                .links(
                    PageLink.builder()
                        .first("https://demo.firefly-iii.org/api/v1/OBJECT?&page=1")
                        .last("https://demo.firefly-iii.org/api/v1/OBJECT?&page=12")
                        .next("https://demo.firefly-iii.org/api/v1/OBJECT?&page=3")
                        .prev("https://demo.firefly-iii.org/api/v1/OBJECT?&page=2")
                        .self("https://demo.firefly-iii.org/api/v1/OBJECT?&page=4")
                        .build()
                )
                .meta(
                    Meta.builder()
                        .pagination(
                            Meta.Pagination.builder()
                                .count(20L)
                                .currentPage(1L)
                                .perPage(100L)
                                .total(3L)
                                .totalPages(1L)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedPiggyBankArray =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(piggyBankArray),
                jacksonTypeRef<PiggyBankArray>(),
            )

        assertThat(roundtrippedPiggyBankArray).isEqualTo(piggyBankArray)
    }
}
