// File generated from our OpenAPI spec by Stainless.

package com.firefly.api.models.accounts

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.firefly.api.core.jsonMapper
import com.firefly.api.models.attachments.ObjectLink
import com.firefly.api.models.recurrences.AccountTypeProperty
import com.firefly.api.models.transactionjournals.TransactionRead
import com.firefly.api.models.transactions.TransactionTypeProperty
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TransactionArrayTest {

    @Test
    fun create() {
        val transactionArray =
            TransactionArray.builder()
                .addData(
                    TransactionRead.builder()
                        .id("2")
                        .attributes(
                            TransactionRead.Attributes.builder()
                                .addTransaction(
                                    TransactionRead.Attributes.Transaction.builder()
                                        .amount("123.45")
                                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                        .description("Vegetables")
                                        .destinationId("2")
                                        .sourceId("2")
                                        .type(TransactionTypeProperty.WITHDRAWAL)
                                        .billId("111")
                                        .billName("Monthly rent")
                                        .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .budgetId("4")
                                        .budgetName("Groceries")
                                        .categoryId("43")
                                        .categoryName("Groceries")
                                        .currencyCode("EUR")
                                        .currencyDecimalPlaces(2)
                                        .currencyId("12")
                                        .currencyName("Euro")
                                        .currencySymbol("\$")
                                        .destinationBalanceAfter("123.45")
                                        .destinationIban("NL02ABNA0123456789")
                                        .destinationName("Buy and Large")
                                        .destinationType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .externalId("external_id")
                                        .externalUrl("external_url")
                                        .foreignAmount("123.45")
                                        .foreignCurrencyCode("USD")
                                        .foreignCurrencyDecimalPlaces(2)
                                        .foreignCurrencyId("17")
                                        .foreignCurrencySymbol("\$")
                                        .hasAttachments(false)
                                        .importHashV2("import_hash_v2")
                                        .interestDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .internalReference("internal_reference")
                                        .invoiceDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .latitude(51.983333)
                                        .longitude(5.916667)
                                        .notes("Some example notes")
                                        .objectHasCurrencySetting(true)
                                        .order(0)
                                        .originalSource("original_source")
                                        .paymentDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .pcAmount("123.45")
                                        .pcDestinationBalanceAfter("123.45")
                                        .pcForeignAmount("123.45")
                                        .pcSourceBalanceAfter("123.45")
                                        .primaryCurrencyCode("EUR")
                                        .primaryCurrencyDecimalPlaces(2)
                                        .primaryCurrencyId("12")
                                        .primaryCurrencySymbol("\$")
                                        .processDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .reconciled(false)
                                        .recurrenceCount(12)
                                        .recurrenceId("recurrence_id")
                                        .recurrenceTotal(0)
                                        .sepaBatchId("sepa_batch_id")
                                        .sepaCc("sepa_cc")
                                        .sepaCi("sepa_ci")
                                        .sepaCountry("sepa_country")
                                        .sepaCtId("sepa_ct_id")
                                        .sepaCtOp("sepa_ct_op")
                                        .sepaDb("sepa_db")
                                        .sepaEp("sepa_ep")
                                        .sourceBalanceAfter("123.45")
                                        .sourceIban("NL02ABNA0123456789")
                                        .sourceName("Checking account")
                                        .sourceType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .subscriptionId("111")
                                        .subscriptionName("Monthly rent")
                                        .addTag("Barbecue preparation")
                                        .transactionJournalId("10421")
                                        .user("3")
                                        .zoomLevel(6)
                                        .build()
                                )
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .groupTitle("Split transaction title.")
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .user("3")
                                .build()
                        )
                        .links(
                            ObjectLink.builder()
                                ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                                .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                                .build()
                        )
                        .type("transactions")
                        .build()
                )
                .links(
                    PageLink.builder()
                        .first("https://demo.firefly-iii.org/api/v1/OBJECT?&page=1")
                        .last("https://demo.firefly-iii.org/api/v1/OBJECT?&page=12")
                        .next("https://demo.firefly-iii.org/api/v1/OBJECT?&page=3")
                        .prev("https://demo.firefly-iii.org/api/v1/OBJECT?&page=2")
                        .self("https://demo.firefly-iii.org/api/v1/OBJECT?&page=4")
                        .build()
                )
                .meta(
                    Meta.builder()
                        .pagination(
                            Meta.Pagination.builder()
                                .count(20L)
                                .currentPage(1L)
                                .perPage(100L)
                                .total(3L)
                                .totalPages(1L)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(transactionArray.data())
            .containsExactly(
                TransactionRead.builder()
                    .id("2")
                    .attributes(
                        TransactionRead.Attributes.builder()
                            .addTransaction(
                                TransactionRead.Attributes.Transaction.builder()
                                    .amount("123.45")
                                    .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                    .description("Vegetables")
                                    .destinationId("2")
                                    .sourceId("2")
                                    .type(TransactionTypeProperty.WITHDRAWAL)
                                    .billId("111")
                                    .billName("Monthly rent")
                                    .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .budgetId("4")
                                    .budgetName("Groceries")
                                    .categoryId("43")
                                    .categoryName("Groceries")
                                    .currencyCode("EUR")
                                    .currencyDecimalPlaces(2)
                                    .currencyId("12")
                                    .currencyName("Euro")
                                    .currencySymbol("\$")
                                    .destinationBalanceAfter("123.45")
                                    .destinationIban("NL02ABNA0123456789")
                                    .destinationName("Buy and Large")
                                    .destinationType(AccountTypeProperty.ASSET_ACCOUNT)
                                    .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .externalId("external_id")
                                    .externalUrl("external_url")
                                    .foreignAmount("123.45")
                                    .foreignCurrencyCode("USD")
                                    .foreignCurrencyDecimalPlaces(2)
                                    .foreignCurrencyId("17")
                                    .foreignCurrencySymbol("\$")
                                    .hasAttachments(false)
                                    .importHashV2("import_hash_v2")
                                    .interestDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .internalReference("internal_reference")
                                    .invoiceDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .latitude(51.983333)
                                    .longitude(5.916667)
                                    .notes("Some example notes")
                                    .objectHasCurrencySetting(true)
                                    .order(0)
                                    .originalSource("original_source")
                                    .paymentDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .pcAmount("123.45")
                                    .pcDestinationBalanceAfter("123.45")
                                    .pcForeignAmount("123.45")
                                    .pcSourceBalanceAfter("123.45")
                                    .primaryCurrencyCode("EUR")
                                    .primaryCurrencyDecimalPlaces(2)
                                    .primaryCurrencyId("12")
                                    .primaryCurrencySymbol("\$")
                                    .processDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .reconciled(false)
                                    .recurrenceCount(12)
                                    .recurrenceId("recurrence_id")
                                    .recurrenceTotal(0)
                                    .sepaBatchId("sepa_batch_id")
                                    .sepaCc("sepa_cc")
                                    .sepaCi("sepa_ci")
                                    .sepaCountry("sepa_country")
                                    .sepaCtId("sepa_ct_id")
                                    .sepaCtOp("sepa_ct_op")
                                    .sepaDb("sepa_db")
                                    .sepaEp("sepa_ep")
                                    .sourceBalanceAfter("123.45")
                                    .sourceIban("NL02ABNA0123456789")
                                    .sourceName("Checking account")
                                    .sourceType(AccountTypeProperty.ASSET_ACCOUNT)
                                    .subscriptionId("111")
                                    .subscriptionName("Monthly rent")
                                    .addTag("Barbecue preparation")
                                    .transactionJournalId("10421")
                                    .user("3")
                                    .zoomLevel(6)
                                    .build()
                            )
                            .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .groupTitle("Split transaction title.")
                            .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                            .user("3")
                            .build()
                    )
                    .links(
                        ObjectLink.builder()
                            ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                            .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                            .build()
                    )
                    .type("transactions")
                    .build()
            )
        assertThat(transactionArray.links())
            .isEqualTo(
                PageLink.builder()
                    .first("https://demo.firefly-iii.org/api/v1/OBJECT?&page=1")
                    .last("https://demo.firefly-iii.org/api/v1/OBJECT?&page=12")
                    .next("https://demo.firefly-iii.org/api/v1/OBJECT?&page=3")
                    .prev("https://demo.firefly-iii.org/api/v1/OBJECT?&page=2")
                    .self("https://demo.firefly-iii.org/api/v1/OBJECT?&page=4")
                    .build()
            )
        assertThat(transactionArray.meta())
            .isEqualTo(
                Meta.builder()
                    .pagination(
                        Meta.Pagination.builder()
                            .count(20L)
                            .currentPage(1L)
                            .perPage(100L)
                            .total(3L)
                            .totalPages(1L)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val transactionArray =
            TransactionArray.builder()
                .addData(
                    TransactionRead.builder()
                        .id("2")
                        .attributes(
                            TransactionRead.Attributes.builder()
                                .addTransaction(
                                    TransactionRead.Attributes.Transaction.builder()
                                        .amount("123.45")
                                        .date(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                        .description("Vegetables")
                                        .destinationId("2")
                                        .sourceId("2")
                                        .type(TransactionTypeProperty.WITHDRAWAL)
                                        .billId("111")
                                        .billName("Monthly rent")
                                        .bookDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .budgetId("4")
                                        .budgetName("Groceries")
                                        .categoryId("43")
                                        .categoryName("Groceries")
                                        .currencyCode("EUR")
                                        .currencyDecimalPlaces(2)
                                        .currencyId("12")
                                        .currencyName("Euro")
                                        .currencySymbol("\$")
                                        .destinationBalanceAfter("123.45")
                                        .destinationIban("NL02ABNA0123456789")
                                        .destinationName("Buy and Large")
                                        .destinationType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .dueDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .externalId("external_id")
                                        .externalUrl("external_url")
                                        .foreignAmount("123.45")
                                        .foreignCurrencyCode("USD")
                                        .foreignCurrencyDecimalPlaces(2)
                                        .foreignCurrencyId("17")
                                        .foreignCurrencySymbol("\$")
                                        .hasAttachments(false)
                                        .importHashV2("import_hash_v2")
                                        .interestDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .internalReference("internal_reference")
                                        .invoiceDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .latitude(51.983333)
                                        .longitude(5.916667)
                                        .notes("Some example notes")
                                        .objectHasCurrencySetting(true)
                                        .order(0)
                                        .originalSource("original_source")
                                        .paymentDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .pcAmount("123.45")
                                        .pcDestinationBalanceAfter("123.45")
                                        .pcForeignAmount("123.45")
                                        .pcSourceBalanceAfter("123.45")
                                        .primaryCurrencyCode("EUR")
                                        .primaryCurrencyDecimalPlaces(2)
                                        .primaryCurrencyId("12")
                                        .primaryCurrencySymbol("\$")
                                        .processDate(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .reconciled(false)
                                        .recurrenceCount(12)
                                        .recurrenceId("recurrence_id")
                                        .recurrenceTotal(0)
                                        .sepaBatchId("sepa_batch_id")
                                        .sepaCc("sepa_cc")
                                        .sepaCi("sepa_ci")
                                        .sepaCountry("sepa_country")
                                        .sepaCtId("sepa_ct_id")
                                        .sepaCtOp("sepa_ct_op")
                                        .sepaDb("sepa_db")
                                        .sepaEp("sepa_ep")
                                        .sourceBalanceAfter("123.45")
                                        .sourceIban("NL02ABNA0123456789")
                                        .sourceName("Checking account")
                                        .sourceType(AccountTypeProperty.ASSET_ACCOUNT)
                                        .subscriptionId("111")
                                        .subscriptionName("Monthly rent")
                                        .addTag("Barbecue preparation")
                                        .transactionJournalId("10421")
                                        .user("3")
                                        .zoomLevel(6)
                                        .build()
                                )
                                .createdAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .groupTitle("Split transaction title.")
                                .updatedAt(OffsetDateTime.parse("2026-04-01T00:00:00+00:00"))
                                .user("3")
                                .build()
                        )
                        .links(
                            ObjectLink.builder()
                                ._0(ObjectLink._0.builder().rel("self").uri("/OBJECTS/1").build())
                                .self("https://demo.firefly-iii.org/api/v1/OBJECTS/1")
                                .build()
                        )
                        .type("transactions")
                        .build()
                )
                .links(
                    PageLink.builder()
                        .first("https://demo.firefly-iii.org/api/v1/OBJECT?&page=1")
                        .last("https://demo.firefly-iii.org/api/v1/OBJECT?&page=12")
                        .next("https://demo.firefly-iii.org/api/v1/OBJECT?&page=3")
                        .prev("https://demo.firefly-iii.org/api/v1/OBJECT?&page=2")
                        .self("https://demo.firefly-iii.org/api/v1/OBJECT?&page=4")
                        .build()
                )
                .meta(
                    Meta.builder()
                        .pagination(
                            Meta.Pagination.builder()
                                .count(20L)
                                .currentPage(1L)
                                .perPage(100L)
                                .total(3L)
                                .totalPages(1L)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedTransactionArray =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(transactionArray),
                jacksonTypeRef<TransactionArray>(),
            )

        assertThat(roundtrippedTransactionArray).isEqualTo(transactionArray)
    }
}
